from datetime import datetime
import os
import modules.session as session

def save_report(title, target, findings, notes):
    try:
        os.makedirs("reports", exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"reports/report_{timestamp}.txt"

        with open(filename, "w") as file:

            file.write("=" * 50 + "\n")
            file.write("CYBERRECONX REPORT\n")
            file.write("=" * 50 + "\n\n")

            file.write(f"Title:  {title}\n")
            file.write(f"Target: {target}\n")
            file.write(
                f"Date:   {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
            )

            file.write("\n" + "-" * 50 + "\n")
            file.write("FINDINGS\n")
            file.write("-" * 50 + "\n")

            if findings:
                for number, finding in enumerate(findings, start=1):
                    file.write(f"{number}. {finding}\n")
            else:
                file.write("No findings recorded.\n")

            file.write("\n" + "-" * 50 + "\n")
            file.write("NOTES\n")
            file.write("-" * 50 + "\n")

            file.write(notes if notes else "No additional notes.")

            file.write("\n\n" + "=" * 50 + "\n")
            file.write("Generated by CyberReconX\n")
            file.write("=" * 50 + "\n")

        return filename

    except Exception as error:
        print(f"Could not save report: {error}")
        return None


def create_report():
    print("\n========================")
    print("Create Report")
    print("========================")

    title = input("Report title: ").strip()
    target = input("Target / Evidence: ").strip()

    findings = []

    print("\nEnter findings.")
    print("Press Enter without typing anything when finished.\n")

    while True:
        finding = input("Finding: ").strip()

        if not finding:
            break

        findings.append(finding)

    notes = input("\nAdditional notes: ").strip()

    filename = save_report(
        title,
        target,
        findings,
        notes
    )

    if filename:
        print("\nReport created successfully.")
        print(f"Saved to: {filename}")


def reporting_menu():

    while True:

        print("\n========================")
        print("Reporting")
        print("========================")

        print("1. Create Manual Report")
        print("2. Generate Last Recon Report")
        print("3. Back")

        choice = input("\nEnter your choice: ").strip()

        if choice == "1":
            create_report()

        elif choice == "2":
            generate_recon_report()

        elif choice == "3":
            break

        else:
            print("Invalid choice.")
def generate_recon_report():

    results = session.last_recon_result

    if results is None:
        print("\nNo Full Recon scan has been performed yet.")
        return

    findings = []

    findings.append(f"Resolved IP: {results['ip']}")
    findings.append(f"Probable OS: {results['os']}")

    if results["open_ports"]:

        for port in results["open_ports"]:
            findings.append(f"Open port detected: {port}")

    else:
        findings.append("No open common ports detected.")

    findings.append(
        f"Scan completed in {results['scan_time']:.2f} seconds"
    )

    filename = save_report(
        title="CyberReconX Full Recon Report",
        target=results["target"],
        findings=findings,
        notes="Automatically generated from the latest Full Recon scan."
    )

    if filename:
        print("\nRecon report generated successfully.")
        print(f"Saved to: {filename}")